GNUREC=-O3 -ffast-math -funroll-all-loops -fpeel-loops -ftracer -funswitch-loops -funit-at-a-time -pthread
GO=$(GNUREC)
CC=g++ $(GO) 

STLPORT=/research/GITHUB/hist_ling/m2m-aligner-1.0/STLport-5.2.1  ## edit here

INCLUDES=-I./tclap1.1.0/include/ -I/research/GITHUB/hist_ling/m2m-aligner-1.0/STLport-5.2.1/stlport
LIBS=-L/research/GITHUB/hist_ling/m2m-aligner-1.0/STLport-5.2.1/build/lib
CFLAGS=-c $(INCLUDES) -DUSESTLPORT
LDFLAGS=$(LIBS) 
INLIBS=-lstlport -lgcc_s -lpthread -lc -lm

alignSrc=mmAligner.cpp mmEM.cpp
SOURCES=$(alignSrc)
alignObj=$(alignSrc:.cpp=.o)
OBJECTS=$(alignObj)

EXECUTABLE=m2m-aligner

all: $($SOURCES) $(EXECUTABLE)

$(EXECUTABLE):	$(OBJECTS) 
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@ $(INLIBS)

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@

clean:	
	rm -f $(EXECUTABLE) $(OBJECTS)
